name: Starter get artifacts
on: 
    push:
        branches:
            - dev
jobs:

    get-artifacts:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Upload artefacts
              uses: actions/upload-artifact@v3
              with:
                names: artefact
                path: SQL/
